config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/new'

  get 'sessions/new'

  resources :dogs
  resources :walkrs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

root 'home#index'

get 'profile' => 'users#show'
get 'dogs' => 'dogs#index'
get 'dog' => 'dogs#show'
get 'dogs/:id' => 'dogs#show'
get 'walkrs' => 'walkrs#index'
get 'walkr' => 'walkrs#show'
get 'walkrs/:id' => 'walkrs#show'

    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :session

end

app/models/walkr.rb
class Walkr < ActiveRecord::Base
  belongs_to :user
  ratyrate_rateable "rating"

end

app/controllers/walkrs_controller.rb
class WalkrsController < ApplicationController
  before_action :set_walkr, only: [:show, :edit, :update, :destroy]

  # GET /walkrs
  # GET /walkrs.json
  def index
    @walkrs = Walkr.all
  end

  # GET /walkrs/1
  # GET /walkrs/1.json
  def show
    @walkr = Walkr.find(params[:id])
  end

  # GET /walkrs/new
  def new
    @walkr = Walkr.new
  end

  # GET /walkrs/1/edit
  def edit
  end

  # POST /walkrs
  # POST /walkrs.json
  def create
    @walkr = Walkr.new(walkr_params)

    respond_to do |format|
      if @walkr.save
        format.html { redirect_to @walkr, notice: 'Walkr was successfully created.' }
        format.json { render :show, status: :created, location: @walkr }
      else
        format.html { render :new }
        format.json { render json: @walkr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walkrs/1
  # PATCH/PUT /walkrs/1.json
  def update
    respond_to do |format|
      if @walkr.update(walkr_params)
        format.html { redirect_to @walkr, notice: 'Walkr was successfully updated.' }
        format.json { render :show, status: :ok, location: @walkr }
      else
        format.html { render :edit }
        format.json { render json: @walkr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walkrs/1
  # DELETE /walkrs/1.json
  def destroy
    @walkr.destroy
    respond_to do |format|
      format.html { redirect_to walkrs_url, notice: 'Walkr was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_walkr
      @walkr = Walkr.find(params[:id])
          if current_user.present?
            unless @walkr.user_id == current_user.id
            flash[:notice] = 'Access denied as you are not this Walkr!'
            redirect_to walkrs_path
          end
          else
            redirect_to signup_path
          end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def walkr_params
      params.require(:walkr).permit(:name, :description, :picture, :rating, :email)
    end
end

app/helpers/walkrs_helper.rb
module WalkrsHelper
end

app/views/walkrs/_form.html.erb
<%= form_for(@walkr) do |f| %>
  <% if @walkr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@walkr.errors.count, "error") %> prohibited this walkr from being saved:</h2>

      <ul>
      <% @walkr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <!-- <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div> -->
  <!-- <div class="actions">
    <%= f.submit %>
  </div> -->

  <div class="pure-button-full"><%= f.submit %></div>

<% end %>

app/views/walkrs/edit.html.erb
<div class="pure-g">

  <div class="pure-u-1">
    <h1 style="margin-left:0.25em; margin-top:1em">Edit a Walkr</h1>
  </div>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path %>  |  <%= link_to 'View this Walkr', @walkr %></p>
</div>

<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3"><img style="max-width:100%" src="<%= @walkr.picture %>" alt="<%= @walkr.name %>" ></div>

<div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2" style="padding:1em">
<%= render 'form' %>
</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path %>  |  <%= link_to 'View this Walkr', @walkr %></p>
</div>

app/views/walkrs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="pure-g">

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <h1 style="margin-left:0.25em">Walkrs</h1>
  </div>

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <div class="pure-button-right" style="margin-right:0.25em; margin-top:2em;"><%= link_to 'Add a Walkr', new_walkr_path %></div>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Picture</h4>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Name & Description</h4>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Rating</h4>
  </div>

</div>

<div class="pure-g">

  <% @walkrs.each do |walkr| %>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
      <img style="max-width:100%" src="<%= walkr.picture %>" alt="<%= walkr.name %>" >
    </div>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3" style="padding:1em">
      <h3><%= link_to walkr.name, walkr_path(walkr) %></h3>
      <p><%= walkr.description %></p>
      <p><a href="mailto:<%= walkr.email %>"><%= walkr.email %></a></p>
      <div class="pure-button-left" style="margin-right:0.25em"><%= link_to 'View Walkr', walkr_path(walkr) %></div>
    </div>


    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3" style="padding:1em; padding-top:2em">
      <p><%= walkr.rating %></p>
      <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
      <% if current_user.present? %>
      <% if walkr.user_id == current_user.id %>
      <p><%= link_to 'Edit', edit_walkr_path(walkr) %></p>
      <p><%= link_to 'Destroy', walkr, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
      <% end %>
     </div>

  <% end %>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left">Group 5, Copyright 2015</p>
</div>

app/views/walkrs/indexOLD.html.erb
<p id="notice"><%= notice %></p>

<div class="pure-g">

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <h1 style="margin-left:0.25em">Walkrs</h1>
  </div>

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <div class="pure-button-right" style="margin-right:0.25em"><%= link_to 'Add a Walkr', new_walkr_path %></div>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Picture</h4>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Name & Description</h4>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Rating</h4>
  </div>

</div>

<div class="pure-g">

  <% @walkrs.each do |walkr| %>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
      <img style="max-width:100%" src="<%= walkr.picture %>" alt="<%= walkr.name %>" >
    </div>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3" style="padding:1em">
      <h3><%= link_to walkr.name, walkr_path(walkr) %></h3>
      <p><%= walkr.description %></p>
      <p><a href="mailto:<%= walkr.email %>"><%= walkr.email %></a></p>
      <div class="pure-button-left" style="margin-right:0.25em"><%= link_to 'View Walkr', walkr_path(walkr) %></div>
    </div>


    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3" style="padding:1em; padding-top:2em">
      <p><%= walkr.rating %></p>
      <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
      <p><%= link_to 'Edit', edit_walkr_path(walkr) %></p>
      <p><%= link_to 'Destroy', walkr, method: :delete, data: { confirm: 'Are you sure?' } %></p>
     </div>

  <% end %>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left">Group 5, Copyright 2015</p>
</div>

app/views/walkrs/new.html.erb
<div class="pure-g">

  <div class="pure-u-1">
    <h1 style="margin-left:0.25em; margin-top:1em">Add a Walkr</h1>
  </div>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path %></p>
</div>

<div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4"><p><br></p></div>

<div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2" style="padding:1em">
<%= render 'form' %>
</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path %></p>
</div>

app/views/walkrs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pure-g">

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <h1 style="margin-left:0.25em">walkrs</h1>
  </div>

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <div class="pure-button-right" style="margin-right:0.25em"><%= link_to 'Add a walkr', new_walkr_path %></div>
  </div>

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path(@walkr) %></p>
  </div>

  <div class="pure-u-1 pure-u-md-3-4 pure-u-lg-3-4">
    <img style="max-width:100%" src="<%= @walkr.picture %>" alt="<%= @walkr.name %>" >
  </div>

  <div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4" style="padding: 1em">
    <h4><%= @walkr.name %></h4>
    <p><%= @walkr.description %><br><br></p>
    <p><a href="mailto:<%= @walkr.email %>"><%= @walkr.email %></a><br><br></p>
    <p><%= @walkr.rating %></p>
    <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
    <p><%= link_to 'Edit', edit_walkr_path(@walkr) %><br><br></p>
    <p><%= link_to 'Destroy', @walkr, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path(@walkr) %></p>
  </div>

</div>