config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/new'

  get 'sessions/new'

  resources :dogs
  resources :walkrs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

root 'home#index'

get 'profile' => 'users#show'
get 'dogs' => 'dogs#index'
get 'dog' => 'dogs#show'
get 'dogs/:id' => 'dogs#show'
get 'walkrs' => 'walkrs#index'
get 'walkr' => 'walkrs#show'
get 'walkrs/:id' => 'walkrs#show'

    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :session

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  ratyrate_rateable "rating"



end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]


  def dog
    @dog = dog
  end

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog.user_id = current_user.id

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
      if current_user.present?
          unless @dog.user_id == current_user.id
          flash[:notice] = 'Access denied as you are not owner of this Dog!'
          redirect_to dogs_path
        end
      else
        redirect_to signup_path 
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :description, :picture, :rating, :email)
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= form_for(@dog) do |f| %>
  <% if @dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% @dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <!-- <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div> -->
  <!-- <div class="actions">
    <%= f.submit %>
  </div> -->

  <div class="pure-button-full"><%= f.submit %></div>

<% end %>

app/views/dogs/edit.html.erb
<div class="pure-g">

  <div class="pure-u-1">
    <h1 style="margin-left:0.25em; margin-top:1em">Edit a Dog</h1>
  </div>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Dogs', dogs_path %>  |  <%= link_to 'View this Dog', @dog %></p>
</div>

<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3"><img style="max-width:100%" src="<%= @dog.picture %>" alt="<%= @dog.name %>" ></div>

<div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2" style="padding:1em">
<%= render 'form' %>
</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Dogs', dogs_path %>  |  <%= link_to 'View this Dog', @dog %></p>
</div>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="pure-g">

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <h1 style="margin-left:0.25em">Dogs</h1>
  </div>

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <div class="pure-button-right" style="margin-right:0.25em; margin-top:2em;"><%= link_to 'Add a Dog', new_dog_path %></div>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Picture</h4>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Name & Description</h4>
  </div>

  <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3 yellow-back">
    <h4>Rating</h4>
  </div>

</div>

<div class="pure-g">

  <% @dogs.each do |dog| %>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3">
      <img style="max-width:100%" src="<%= dog.picture %>" alt="<%= dog.name %>" >
    </div>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3" style="padding:1em">
      <h4><%= link_to dog.name, dog_path(dog) %></h4>
      <p><%= dog.description %></p>
      <p><a href="mailto:<%= dog.email %>"><%= dog.email %></a></p>
      <div class="pure-button-left" style="margin-right:0.25em"><%= link_to 'View Dog', dog_path(dog) %></div>
    </div>

    <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3" style="padding:1em; padding-top:2em">
      <p><%= dog.rating %></p>
      <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
      <% if current_user.present? %>
      <% if dog.user_id == current_user.id %>
      <p><%= link_to 'Edit', edit_dog_path(dog) %></p>
      <p><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
      <% end %>

     </div>

  <% end %>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left">Group 5, Copyright 2015</p>
</div>

app/views/dogs/new.html.erb
<div class="pure-g">

  <div class="pure-u-1">
    <h1 style="margin-left:0.25em; margin-top:1em">Add a Dog</h1>
  </div>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Dogs', dogs_path %></p>
</div>

<div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4"><p><br></p></div>

<div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2" style="padding:1em">
<%= render 'form' %>
</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'Back to all Dogs', dogs_path %></p>
</div>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="pure-g">

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <h1 style="margin-left:0.25em">Dogs</h1>
  </div>

  <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2">
    <div class="pure-button-right" style="margin-right:0.25em"><%= link_to 'Add a Dog', new_dog_path %></div>
  </div>

</div>

<div class="pure-g">

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'Back to all Dogs', dogs_path(@dog) %></p>
  </div>

  <div class="pure-u-1 pure-u-md-3-4 pure-u-lg-3-4">
    <img style="max-width:100%" src="<%= @dog.picture %>" alt="<%= @dog.name %>" >
  </div>

  <div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4" style="padding: 1em">
    <h4><%= @dog.name %></h4>
    <p><%= @dog.description %><br><br></p>
    <p><a href="mailto:<%= @dog.email %>"><%= @dog.email %></a><br><br></p>
    <p><%= @dog.rating %>
      <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
      <br><br></p>
    <p><%= link_to 'Edit', edit_dog_path(@dog) %><br><br></p>
    <p><%= link_to 'Destroy', @dog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'Back to all Dogs', dogs_path(@dog) %></p>
  </div>

</div>