config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/new'

  get 'sessions/new'

  resources :dogs
  resources :walkrs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

root 'home#index'

get 'profile' => 'users#show'
get 'dogs' => 'dogs#index'
get 'dog' => 'dogs#show'
get 'dogs/:id' => 'dogs#show'
get 'walkrs' => 'walkrs#index'
get 'walkr' => 'walkrs#show'
get 'walkrs/:id' => 'walkrs#show'

    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :session

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :walkrs
  has_many :dogs
  has_many :user_ratings
  ratyrate_rater

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
  # Returns the hash digest of the given string.
   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  # def remember
  #   self.remember_token = User.new_token
  #   update_attribute(:remember_digest, User.digest(remember_token))
  # end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  # def forget
  #   update_attribute(:remember_digest, nil)
  # end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :logged_in_user, only: [:index, :edit, :update]
 before_action :correct_user,   only: [:edit, :update]
 # before_action :job_owner, only: [:edit, :update, :destroy, :show]



  # def job_owner
  #
  # end


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Walkr!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  private
    def user_params
       params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

     # Before filters



    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
      #
      # def index
      #    @users = User.all
      #    @user = currect_user
      #  end

    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="pure-g">

  <div class="pure-u-1">
    <h1 style="margin-left:0.25em; margin-top:1em">Edit User</h1>
  </div>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'View this User', @user %></p>
</div>

<div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-3"><img style="max-width:100%" src="<%= @user.picture %>" alt="<%= @user.name %>" ></div>

<div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2" style="padding:1em">

  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <%= f.submit "Save changes", class: "btn btn-primary" %>
  <% end %>

  <div class="gravatar_edit">
    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>

</div>

<div class="pure-u-1 yellow-back">
  <p class="is-left"><%= link_to 'View this User', @user %></p>
</div>


# default form content below
#
# <% provide(:title, "Edit user") %>
# <h1>Update your profile</h1>
#
# <div class="row">
#   <div class="col-md-6 col-md-offset-3">
#     <%= form_for(@user) do |f| %>
#       <%= render 'shared/error_messages' %>
#
#       <%= f.label :name %>
#       <%= f.text_field :name, class: 'form-control' %>
#
#       <%= f.label :email %>
#       <%= f.email_field :email, class: 'form-control' %>
#
#       <%= f.label :password %>
#       <%= f.password_field :password, class: 'form-control' %>
#
#       <%= f.label :password_confirmation, "Confirmation" %>
#       <%= f.password_field :password_confirmation, class: 'form-control' %>
#
#       <%= f.submit "Save changes", class: "btn btn-primary" %>
#     <% end %>
#
#   </div>
# </div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<% provide(:title, @user.name) %>

<div class="pure-g">
  <div class="pure-u-1 yellow-back"><p><br></p></div>

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path(@walkr) %></p>
  </div>

  <div class="pure-u-1 pure-u-md-3-4 pure-u-lg-3-4">

  </div>

  <div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4" style="padding: 1em">
    <h4><%= @user.name %></h4>

    <p><%= @user.type %><br><br></p>
    <p><a href="mailto:<%= @user.email %>"><%= @user.email %></a><br><br></p>
    <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
  </div>

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'Back to all Walkrs', walkrs_path(@walkr) %></p>
  </div>

</div>
>>>>>>> 38593daf045427eb801f56ef9b28a69d3c412243

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="pure-g">

  <div class="pure-u-1">
    <h1 style="margin-left:0.25em; margin-top:1em">Sign up</h1>
  </div>

</div>

<div class="pure-u-1 yellow-back"><p><br></p></div>

<div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4"><p><br></p></div>

<div class="pure-u-1 pure-u-md-1-2 pure-u-lg-1-2" style="padding:1em">

  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>

    <div class="pure-button-full">
    <%= f.submit "Sign up" %>
    </div>
  <% end %>


</div>

<div class="pure-u-1 yellow-back"><p><br></p></div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="pure-g">
  <div class="pure-u-1 yellow-back"><p><br></p></div>

  <div class="pure-u-1 yellow-back">
    <p class="is-left"><%= link_to 'View Walkrs', walkrs_path(@walkr) %> | <class="is-left"><%= link_to 'View Dogs', dogs_path(@dog) %></p>
  </div>

  <div class="pure-u-1 pure-u-md-3-4 pure-u-lg-3-4">

  </div>

  <div class="pure-u-1 pure-u-md-1-4 pure-u-lg-1-4" style="padding: 1em">
    <h4><%= @user.name %></h4>

    <p><a href="mailto:<%= @user.email %>"><%= @user.email %></a><br><br></p>
    <i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="color:red; font-size:30px"></i><i class="fa fa-star" style="font-size:30px"></i>
  </div>

  <div class="pure-u-1 yellow-back">
    <p><br>
    </p>
  </div>

</div>