config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'users/new'

  get 'sessions/new'

  resources :dogs
  resources :walkrs
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

root 'home#index'

get 'profile' => 'users#show'
get 'dogs' => 'dogs#index'
get 'dog' => 'dogs#show'
get 'dogs/:id' => 'dogs#show'
get 'walkrs' => 'walkrs#index'
get 'walkr' => 'walkrs#show'
get 'walkrs/:id' => 'walkrs#show'

    get 'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :session

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Walkr</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">

</head>

<body>
  <header>
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
      <a class="pure-menu-heading" href="/">Walkr</a>

      <ul class="pure-menu-list">
          <% if logged_in? %>
              <% puts "i see this" %>
              <li class="pure-menu-item"><a href="/dogs/" class="pure-menu-link">Dogs</a></li>
              <li class="pure-menu-item"><a href="/walkrs/" class="pure-menu-link">Walkrs</a></li>
              <li class="pure-menu-item"><%= link_to "Profile", user_path(current_user), class: "pure-menu-link" %></li>
              <li class="pure-menu-item"><%= link_to "Log out", logout_path, method: "delete", class: "pure-menu-link" %></li>

          <% else %>
              <li class="pure-menu-item"><a href="/dogs/" class="pure-menu-link">Dogs</a></li>
              <li class="pure-menu-item"><a href="/walkrs/" class="pure-menu-link">Walkrs</a></li>
              <li class="pure-menu-item"><a href="/signup/" class="pure-menu-link">Sign Up</a></li>
              <li class="pure-menu-item"><a href="/login/" class="pure-menu-link">Log In</a></li>
          <% end %>

      </ul>
    </div>

  </header>

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>

</body>
</html>